[tool.poetry]
name = "Package Manager"
version = "0.1.0"
description = ""
authors = ["CnSiva <sivacn@btclabs.cloud>"]

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"

